language: node_js

node_js:
  - 10.16

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install

script:
  - npm run lint
  - npm run test

cache:
  directories:
    - node_modules